# Generated by Django 4.1.4 on 2022-12-13 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive_axle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Engine_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Service_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Steerable_axle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Technique_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.TextField(max_length=17, unique=True, verbose_name='Заводской номер')),
                ('engine_number', models.TextField(max_length=17, verbose_name='Номер двигателя')),
                ('transmission_number', models.TextField(max_length=50, verbose_name='Номер трансмиссии')),
                ('drive_axle_number', models.TextField(max_length=50, verbose_name='Номер ведущего моста')),
                ('steerable_axle_number', models.TextField(max_length=50, verbose_name='Номер управляемого моста')),
                ('supply_contract', models.TextField(max_length=50, verbose_name='Договор поставки №, дата.')),
                ('date_of_shipment_from_the_factory', models.DateTimeField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.TextField(max_length=50, verbose_name='Грузополучатель')),
                ('delivery_address', models.TextField(max_length=150, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(max_length=150, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.drive_axle_model')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.engine_model')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.service_company', verbose_name='Сервисная компания')),
                ('steerable_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.steerable_axle_model')),
                ('technique_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.technique_model')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.transmission_model')),
            ],
        ),
    ]
